version: "3.9"

services:
  # Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dev-docker-repository:pathwise-hcm-1.0.0
    container_name: pathwise-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    restart: unless-stopped
    depends_on:
      - milvus
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  # Milvus
  milvus:
    image: milvusdb/milvus:v2.3.9
    container_name: pathwise-milvus
    restart: unless-stopped
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus

volumes:
  milvus_data:
